"""Exercise the shipped zipapp's process-level 0/1/2 contract.

This deliberately invokes the archive as a user does. Importing ``cli.main``
would miss defects in the top-level ``__main__.py`` generated by zipapp.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile


def _run(command: list[str], cwd: Path) -> subprocess.CompletedProcess[bytes]:
    return subprocess.run(
        command,
        cwd=cwd,
        capture_output=True,
        env={
            **os.environ,
            "GIT_CONFIG_GLOBAL": os.devnull,
            "GIT_CONFIG_NOSYSTEM": "1",
            "GIT_TERMINAL_PROMPT": "0",
            "GREENWASH_TODAY": "2026-01-01",
            "NO_COLOR": "1",
            "PYTHONUTF8": "1",
        },
    )


def _git(repo: Path, *args: str) -> None:
    result = _run(["git", *args], repo)
    if result.returncode != 0:
        raise RuntimeError(result.stderr.decode("utf-8", "replace"))


def _expect_exit(
    pyz: Path,
    repo: Path,
    expected: int,
    *args: str,
) -> subprocess.CompletedProcess[bytes]:
    result = _run([sys.executable, str(pyz), *args], repo)
    if result.returncode != expected:
        stdout = result.stdout.decode("utf-8", "replace")
        stderr = result.stderr.decode("utf-8", "replace")
        raise RuntimeError(
            f"greenwash.pyz {' '.join(args)} exited {result.returncode}, expected {expected}\n"
            f"stdout:\n{stdout}\nstderr:\n{stderr}"
        )
    return result


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise RuntimeError(message)


def qualify(pyz: Path) -> None:
    pyz = pyz.resolve(strict=True)
    with tempfile.TemporaryDirectory(prefix="greenwash-pyz-qualification-") as temporary:
        repo = Path(temporary)
        _git(repo, "init", "-b", "main")
        _git(repo, "config", "user.name", "greenwash zipapp qualification")
        _git(repo, "config", "user.email", "zipapp@example.invalid")
        _git(repo, "config", "commit.gpgsign", "false")

        version = _expect_exit(pyz, repo, 0, "--version")
        _require(version.stdout.startswith(b"greenwash "), "--version output is malformed")
        demo = _expect_exit(pyz, repo, 0, "demo")
        _require(b"tampering cases blocked" in demo.stdout, "demo summary is missing")

        (repo / "billing.py").write_text(
            "def invoice_total(subtotal):\n    return subtotal\n",
            encoding="utf-8",
        )
        tests = repo / "tests"
        tests.mkdir()
        test_file = tests / "test_billing.py"
        test_file.write_text(
            "from billing import invoice_total\n\n\n"
            "def test_invoice_total():\n"
            "    assert invoice_total(105.3) == 105.3\n",
            encoding="utf-8",
        )
        _git(repo, "add", "billing.py", "tests/test_billing.py")
        _git(repo, "commit", "-m", "baseline exact assertion")

        clean = _expect_exit(pyz, repo, 0, "check", "HEAD..HEAD", "--format", "json")
        _require(json.loads(clean.stdout).get("verdict") == "pass", "clean JSON verdict is not pass")
        clean_hook = _expect_exit(
            pyz,
            repo,
            0,
            "check",
            "HEAD..HEAD",
            "--format",
            "hook-json",
        )
        _require(json.loads(clean_hook.stdout) == {}, "clean hook-json payload is not empty")

        test_file.write_text(
            test_file.read_text(encoding="utf-8").replace(
                "assert invoice_total(105.3) == 105.3",
                "assert invoice_total(105.3) > 0",
            ),
            encoding="utf-8",
        )
        _git(repo, "add", "tests/test_billing.py")
        _git(repo, "commit", "-m", "weaken assertion")

        blocked = _expect_exit(
            pyz,
            repo,
            1,
            "check",
            "HEAD~1..HEAD",
            "--format",
            "json",
        )
        payload = json.loads(blocked.stdout)
        _require(payload.get("verdict") == "block", "blocking JSON verdict is not block")
        _require(
            any(finding.get("rule") == "ASSERT_WEAKENED" for finding in payload.get("findings", [])),
            "blocking JSON payload has no ASSERT_WEAKENED finding",
        )

        term = _expect_exit(pyz, repo, 1, "check", "HEAD~1..HEAD", "--format", "term")
        _require(b"ASSERT_WEAKENED" in term.stdout, "term output has no ASSERT_WEAKENED finding")
        _require(b"verdict=block" in term.stdout, "term output has no block verdict")

        sarif = _expect_exit(pyz, repo, 1, "check", "HEAD~1..HEAD", "--format", "sarif")
        sarif_payload = json.loads(sarif.stdout)
        _require(sarif_payload.get("version") == "2.1.0", "SARIF version is not 2.1.0")
        sarif_runs = sarif_payload.get("runs", [])
        _require(bool(sarif_runs), "SARIF payload has no runs")
        _require(
            any(
                result.get("ruleId") == "ASSERT_WEAKENED"
                for result in sarif_runs[0].get("results", [])
            ),
            "SARIF payload has no ASSERT_WEAKENED result",
        )

        hook = _expect_exit(
            pyz,
            repo,
            0,
            "check",
            "HEAD~1..HEAD",
            "--format",
            "hook-json",
        )
        hook_payload = json.loads(hook.stdout)
        _require(hook_payload.get("decision") == "block", "hook-json decision is not block")
        hook_reason = hook_payload.get("reason")
        _require(isinstance(hook_reason, str) and bool(hook_reason.strip()), "hook-json reason is empty")
        _require("ASSERT_WEAKENED" in hook_reason, "hook-json reason has no ASSERT_WEAKENED finding")

        failed = _expect_exit(pyz, repo, 2, "check", "MISSING_REF..HEAD", "--format", "json")
        _require(b"greenwash engine error" in failed.stderr, "bad ref has no engine error")
        bad_range = _expect_exit(pyz, repo, 2, "check", "HEAD")
        _require(b"range must be BASE..HEAD" in bad_range.stderr, "bad range has no range error")
        typo = _expect_exit(pyz, repo, 2, "chek")
        _require(b"Did you mean 'check'?" in typo.stderr, "command typo has no suggestion")


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    if len(args) != 1:
        print("usage: python tools/qualify_zipapp.py PATH/greenwash.pyz", file=sys.stderr)
        return 2
    try:
        qualify(Path(args[0]))
    except (OSError, RuntimeError, ValueError) as error:
        print(f"zipapp qualification failed: {error}", file=sys.stderr)
        return 1
    print(
        "zipapp qualification passed: version/demo/clean=0; term/json/sarif block=1; "
        "bad ref/range/typo=2; hook-json clean={} and block decision both exit 0"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
